//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextHighlightCore {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class HightlightSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HightlightSettings defaultInstance = ((HightlightSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HightlightSettings())));
        
        public static HightlightSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
